# Minimal configuration

[[server]]
name = "1594394042366431232"
port = 25

[[target]]
name = "1594394042366431232"
url = "stratum+tcp://stratum.slushpool.com:3333"
user_identity = "3LHEJozXt3xhKuuwPmWTpuEciXYGfQhQP8.10x32"

[[routing]]
from = ["stratum+tcp://ss.antpool.com:25"]

[[routing.goal]]
name = "www.antpool.com"

[[routing.goal.level]]
targets = ["100"]
