# Minimal configuration

[[server]]
name = "stratum+tcp://ss.antpool.com:25"
port = 25

[[target]]
name = "stratum+tcp://ss.antpool.com:25"
url = "stratum+tcp://stratum.slushpool.com:3333"
user_identity = "3LHEJozXt3xhKuuwPmWTpuEciXYGfQhQP8.10x32"

[[routing]]
from = ["stratum+tcp://ss.antpool.com:25"]

[[routing.goal]]
name = "Primary Goal"

[[routing.goal.level]]
targets = ["SP"]
