# Full server configuration
[[server]]
name = "1594394042366431232"
port = 25

# Minimal server configuration
[[server]]
name = "1594394042366431232"
port = 25

# Full target configuration
[[target]]
name = "www.antpool.com"
url = "stratum+tcp://ss.antpool.com:25"
user_identity = "3LHEJozXt3xhKuuwPmWTpuEciXYGfQhQP8.10x32"

[[target]]
name = "www.antpool"
url = "stratum+tcp://ss.antpool.com:25"
user_identity = "3LHEJozXt3xhKuuwPmWTpuEciXYGfQhQP8.10x32"

[[routing]]
from = ["S1", "S2"]

[[routing.goal]]
hr_weight = 100
name = "Goal 100%"

[[routing.goal.level]]
targets = ["SP-US"]

[[routing.goal.level]]
targets = ["SP-EU"]
